
services:
  app:
    container_name: customer_app
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - .:/go/src  
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=encoder
    ports:
      - "5432:5432"  